# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 15
  - name: Topics
    url: tags/
    weight: 25
  - name: Uses
    url: uses/
    weight: 35
