# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 8
  - name: Publications
    url: tags/
    weight: 18
  - name: Experience
    url: uses/
    weight: 28
