# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 18
  - name: Publications
    url: uses/
    weight: 28
  - name: Experience
    url: Honors/
    weight: 38
